server:
  port: 8081

spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://192.168.1.14:3306/user_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: cherry1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  rabbitmq:
    addresses: 192.168.1.14
    port: 5672
    virtual-host: 192.168.1.14
    username: dev1
    password: dev123456
  elasticsearch:
    uris: http://192.168.1.14:9200
    username: elastic
    password: dev123456

cherry:
  rabbit:
    addUserQueueName: rabbit.add.user